<?php
use YooKassa\Common\Exceptions\ApiException;
use YooKassa\Model\Payment;
use YooKassa\Model\PaymentStatus;
use YooKassa\Request\Payments\CreatePaymentRequest;
use YooKassa\Request\Payments\CreatePaymentRequestBuilder;
use YooKassa\Request\Payments\Payment\CreateCaptureRequest;
use YooKassa\Request\Payments\Payment\CreateCaptureRequestBuilder;

$modulePath = drupal_get_path('module', 'yoomoney_api');
require_once $modulePath.DIRECTORY_SEPARATOR.'YooMoneyLogger.php';
require_once $modulePath.DIRECTORY_SEPARATOR.'YooMoneyInstallments.php';
define('YOOMONEY_EVENT_ORDER_UPDATE', 'update');


/**
 * @param $event
 * @param $order
 * @param $new_status
 */
function yoo_ubercart_api_uc_order($event, $order, $new_status){
    if ($event != YOOMONEY_EVENT_ORDER_UPDATE) {
        return;
    }

    if (!yoomoney_api_is_need_second_receipt($new_status)) {
        return;
    }

    $orderInfo = array(
        'order_id'   => $order->order_id,
        'user_email' => empty($order->primary_email) ? null : $order->primary_email,
        'user_phone' => empty($order->billing_phone) ? null : $order->billing_phone,
    );

    $result = yoomoney_api_send_second_receipt($orderInfo);

    if (!$result->is_send) {
        return;
    }

    uc_order_comment_save($order->order_id, $order->uid, $result->message, 'admin', $status = $new_status);
}

/**
 * Implements hook_uc_payment_method().
 *
 * @see uc_payment_method_yoomoney_api()
 */
function yoo_ubercart_api_uc_payment_method()
{
    $payment_methods = array();
    $icon_name       = (variable_get('yoomoney_api_shop', 0) == 0) ? 'yoomoney-logo' : 'yookassa-logo';
    $icon            = theme(
        'image',
        array(
            'path'       => drupal_get_path('module', 'yoo_ubercart_api').'/images/'.$icon_name.'.png',
            'attributes' => array('class' => array('yoo-ubercart-logo')),
        )
    );

    $display_title = '';
    if (variable_get('yoomoney_api_shop', 0)) {
        $display_title = t('YooKassa (bank card, e-money, etc.)');
    } else if (variable_get('yoomoney_api_p2p', 0)) {
        $display_title = t('YooMoney (bank card, e-wallet)');
    }

    $display_title                      .= '<br/>'.$icon;
    $payment_methods['yoo_ubercart_api'] = array(
        'name'     => t('YooMoney'),
        'title'    => $display_title,
        'review'   => t('YooMoney gateway'),
        'desc'     => t('Redirect to YooMoney to pay by credit card or pay terminals or e-money.'),
        'callback' => 'uc_payment_method_yoo_ubercart_api',
        'redirect' => 'yoo_ubercart_api_form',
        'weight'   => 3,
        'checkout' => true,
    );

    return $payment_methods;
}

/**
 * @param array $form
 * @param array $form_state
 * @param $order
 *
 * @return array
 * @throws Exception
 */
function yoo_ubercart_api_form($form, &$form_state, $order)
{
    global $user;

    if (variable_get('yoomoney_api_shop', 1)) {
        if (isset($form_state['input']['confirmation'])) {
            drupal_goto($form_state['input']['confirmation']);
            uc_order_update_status($order->order_id, 'payment_received');
        }

        $modulePath = drupal_get_path('module', 'yoomoney_api');
        require_once $modulePath.DIRECTORY_SEPARATOR.'vendor'.DIRECTORY_SEPARATOR.'autoload.php';
        $apiClient = yoomoney_api__common__get_api_client();

        $amount = $order->order_total;
        if (isset($_SESSION['pay_method'])) {
            $paymentMethod = $_SESSION['pay_method'];
        } else {
            $paymentMethod = '';
        }

        $builder        = yoo_ubercart_api_get_create_payment_request_builder($order, $amount, $paymentMethod);
        $paymentRequest = $builder->build();

        try {
            $response = $apiClient->createPayment($paymentRequest, $order->order_id.'_'.$paymentMethod);
            if ($response->status !== PaymentStatus::CANCELED) {
                $transaction             = new YooMoneyApiTransaction();
                $transaction->uid        = $user->uid;
                $transaction->amount     = $order->order_total;
                $transaction->mail       = isset($user->mail) ? $user->mail : $order->primary_email;
                $transaction->order_id   = $order->order_id;
                $transaction->payment_id = $response->getId();
                $transaction->status     = $response->getStatus();
                if (!yoomoney_api_transaction_save($transaction)) {
                    $error_message = t('Can not save transaction.');

                    // show message to the user
                    drupal_set_message(t('Payment failed: %message', array('%message' => $error_message)), 'error');

                    // log error to watchdog
                    watchdog('yoo_ubercart', 'Payment failed: %message', array('%message' => $error_message),
                        WATCHDOG_WARNING);
                    // redirect to fail page
                    $cancel_url = url('yoomoney_api/fail');
                    drupal_goto($cancel_url);
                }

                uc_order_update_status($order->order_id, 'pending');
                $confirmationUrl                        = $response->confirmation->confirmationUrl;
                $form['actions']['submit']['#submit'][] = 'yoo_ubercart_api_redirect_handler';
                $form['actions']['submit']              = array(
                    '#type'       => 'submit',
                    '#value'      => t('Process payment'),
                    '#attributes' => array('onclick' => "location.href = '{$confirmationUrl}'; return false;"),
                );

                return $form;
            } else {
                drupal_set_message('Невозможно заплатить этим методом', 'error');
            }
        } catch (ApiException $e) {
            YooMoneyLogger::error('Api error: '.$e->getMessage());
            drupal_set_message('Unable to pay with this method.', 'error');
        }
    } else {
        $transaction           = new YooMoneyApiTransaction();
        $transaction->uid      = $user->uid;
        $transaction->amount   = $order->order_total;
        $transaction->mail     = isset($user->mail) ? $user->mail : $order->primary_email;
        $transaction->order_id = $order->order_id;
        $form                  = array();
        if (!yoomoney_api_transaction_save($transaction)) {
            $error_message = t('Can not save transaction.');

            // show message to the user
            drupal_set_message(t('Payment failed: %message', array('%message' => $error_message)), 'error');

            // log error to watchdog
            watchdog('yoo_ubercart', 'Payment failed: %message', array('%message' => $error_message), WATCHDOG_WARNING);

            // redirect to fail page
            $cancel_url = url('yoomoney_api/fail');
            drupal_goto($cancel_url);
        }

        $target_url      = yoomoney_api_get_order_submission_url();
        $params          = yoomoney_api_get_order_submission_params($transaction);
        $form['#action'] = $target_url;
        foreach ($params as $key => $value) {
            if ($key == 'fio') {
                $form[$key] = array(
                    '#type'  => 'hidden',
                    '#value' => $order->data['customer_name'],
                );
            } else {
                $form[$key] = array(
                    '#type'  => 'hidden',
                    '#value' => $value,
                );
            }
        }

        $form['cms_name'] = array(
            '#type'  => 'hidden',
            '#value' => "drupal-ubercart",
        );

        $form['actions']           = array('#type' => 'actions');
        $form['actions']['submit'] = array(
            '#type'  => 'submit',
            '#value' => t('Submit order'),
        );
    }

    return $form;
}

/**
 * @param $order
 * @param $amount
 * @param $paymentMethod
 *
 * @return \YooKassa\Request\Payments\CreatePaymentRequestBuilder
 */
function yoo_ubercart_api_get_create_payment_request_builder($order, $amount, $paymentMethod)
{
    $confirmationType = \YooKassa\Model\ConfirmationType::REDIRECT;

    if ($paymentMethod == 'alfabank') {
        $confirmationType = \YooKassa\Model\ConfirmationType::EXTERNAL;
        $paymentMethod    = new \YooKassa\Model\PaymentData\PaymentDataAlfabank();
        try {
            $paymentMethod->setLogin($_SESSION['alfabank_login']);
        } catch (Exception $e) {
            drupal_set_message(t('The login field is filled incorrectly.'), 'error');
        }
    } elseif ($paymentMethod == 'qiwi') {
        $paymentMethod = new \YooKassa\Model\PaymentData\PaymentDataQiwi();
        try {
            $paymentMethod->setPhone($_SESSION['qiwi_phone']);
        } catch (Exception $e) {
            drupal_set_message(t('The phone number field is filled incorrectly.'), 'error');
        }
    }

    $builder = CreatePaymentRequest::builder()
                                   ->setAmount($amount)
                                   ->setPaymentMethodData($paymentMethod)
                                   ->setCapture(yoomoney_api__common__get_capture_value($paymentMethod))
                                   ->setDescription(yoo_ubercart_api_create_description($order))
                                   ->setConfirmation(array(
                                           'type'      => $confirmationType,
                                           'returnUrl' => yoo_ubercart_api_get_return_url($order),
                                   ))
                                   ->setMetadata(array(
                                       'cms_name'       => 'yoo_api_drupal_ubercart',
                                       'module_version' => YOOMONEY_MODULE_VERSION,
                                   ));
    yoo_ubercart_api_set_receipt_if_needed($builder, $order);

    return $builder;
}

/**
 * @param CreatePaymentRequestBuilder|CreateCaptureRequestBuilder $builder
 * @param $order
 */
function yoo_ubercart_api_set_receipt_if_needed($builder, $order)
{
    $tax = uc_taxes_uc_calculate_tax($order);
    if (module_exists('uc_taxes') && variable_get('yoomoney_api_send_check', false)) {
        $builder->setReceiptEmail($order->primary_email);

        if (count($tax)) {
            $tax = current($tax);
        }

        foreach ($order->products as $product) {
            $tax_id = isset($tax->id) ? $tax->id : 0;
            $tax    = ($tax_id && variable_get('yoomoney_api_kassa_tax_'.$tax_id) ? variable_get(
                'yoomoney_api_kassa_tax_'.$tax_id
            ) : YOOMONEY_API_DEFAULT_TAX_RATE_ID);
            list($amountTax, $suffixes) = uc_taxes_get_included_tax($product, $order);
            $amount = $product->price + ($amountTax ? $amountTax : 0);
            $builder->addReceiptItem($product->title, $amount, $product->qty, $tax,
                variable_get('yoomoney_kassa_payment_mode'),
                variable_get('yoomoney_kassa_payment_subject'));
        }

        foreach ($order->line_items as $item) {
            if ($item['type'] === 'subtotal') {
                continue;
            }
            $tax_id = isset($tax->id) ? $tax->id : 0;
            $amount = $item['amount'] * (isset($tax->id) ? (1 + $tax->data['tax_rate']) : 1);
            $tax    = ($tax_id && variable_get('yoomoney_api_kassa_tax_'.$tax_id) ? variable_get(
                'yoomoney_api_kassa_tax_'.$tax_id
            ) : YOOMONEY_API_DEFAULT_TAX_RATE_ID);

            $builder->addReceiptShipping($item['title'], $amount, $tax,
                variable_get('yoomoney_kassa_delivery_payment_mode'),
                variable_get('yoomoney_kassa_delivery_payment_subject'));
        }
    }
}

/**
 * Implements hook_yoomoney_api_shop_params_alter().
 *
 * @param $params
 */
function yoo_ubercart_api_yoomoney_api_shop_params_alter(&$params)
{
    // Selected payment method
    $params['paymentType'] = (variable_get('yoomoney_api_paymode') == 'shop') ? $_SESSION['pay_method'] : '';
    $params['shop-desc']   = t('Payments for order No').$params['order_id'];
}

/**
 * Implements hook_yoomoney_api_quick_params_alter().
 *
 * @param $params
 */
function yoo_ubercart_api_yoomoney_quick_params_alter(&$params)
{
    // Selected payment method
    $params['paymentType'] = @$_SESSION['pay_method'];
}

/**
 * @param $op
 * @param $order
 * @param null $form
 * @param null $form_state
 *
 * @return array|null
 */
function uc_payment_method_yoo_ubercart_api($op, &$order, $form = array(), &$form_state = array())
{
    switch ($op) {
        case 'cart-details':
            $form     = array();
            $disabled = false;
            $methods  = yoomoney_api_get_enabled_payment_methods();

            if (isset($order->order_total) && ($order->order_total < YOOMONEY_API_INSTALLMENTS_MIN_AMOUNT)) {
                unset($methods[\YooKassa\Model\PaymentMethodType::INSTALLMENTS]);
            }

            if (isset($order->order_total) && isset($methods[\YooKassa\Model\PaymentMethodType::INSTALLMENTS])) {
                $shopId             = variable_get('yoomoney_api_shop_id');
                $monthlyInstallment = YooMoneyInstallments::creditPreSchedule($shopId, $order->order_total);
                if (!empty($monthlyInstallment['amount'])) {
                    $methods[\YooKassa\Model\PaymentMethodType::INSTALLMENTS] = sprintf(
                        t('Installments (%s ₽ per month)'),
                        $monthlyInstallment['amount']
                    );
                } else {
                    $errorMessage = YooMoneyInstallments::getLastError() ?: 'Unknown error. Could not get installment amount';
                    YooMoneyLogger::error($errorMessage);
                }
            }

            if (count($methods) === 1) {
                $disabled = true;
            }

            if (variable_get('yoomoney_api_paymode') == 'shop' && variable_get('yoo_payments_select', 1)) {
                $defaultValue = isset($_SESSION['pay_method'])
                                ? $_SESSION['pay_method']
                                : variable_get('yoomoney_api_default_payment_method', YOOMONEY_API_DEFAULT_PAYMENT_METHOD);

                if (!isset($methods[$defaultValue])) {
                    $defaultValue = isset($methods[YOOMONEY_API_DEFAULT_PAYMENT_METHOD])
                        ? YOOMONEY_API_DEFAULT_PAYMENT_METHOD
                        : key($methods);
                }

                $form['pay_method'] = array(
                    '#type'          => 'radios',
                    '#title'         => t('Select your payment type:'),
                    '#default_value' => $defaultValue,
                    '#prefix'        => '<div id="ym-payment_methods">',
                    '#options'       => $methods,
                    '#disabled'      => $disabled,
                    '#theme'         => 'form_radios_element',
                    '#ajax'          => array(
                        'callback' => 'yoo_ubercart_ajax_payment_method_form_callback',
                        'method'   => 'replace',
                        'effect'   => 'fade',
                        'wrapper'  => 'ym-payment_methods',
                    ),
                );
                unset($_SESSION['pay_method']);

                return $form;
            }

            if (variable_get('yoomoney_api_p2p', 0)) {
                $form['pay_method'] = array(
                    '#type'          => 'radios',
                    '#title'         => t('Select your payment type:'),
                    '#default_value' => 'AC',
                    '#prefix'        => '<div id="ym-payment_methods">',
                    '#options'       => $methods,
                    '#disabled'      => $disabled,
                    '#theme'         => 'form_radios_element',
                    '#ajax'          => array(
                        'callback' => 'yoo_ubercart_ajax_payment_method_form_callback',
                        'method'   => 'replace',
                        'effect'   => 'fade',
                        'wrapper'  => 'ym-payment_methods',
                    ),
                );

                return $form;
            }
            break;
        case 'cart-process':

            if (isset($form_state['values']['panes']['payment']['details']['pay_method'])) {
                $paymentMethod          = $form_state['values']['panes']['payment']['details']['pay_method'];
                $_SESSION['pay_method'] = $paymentMethod;
                if ($paymentMethod == 'alfabank') {
                    $_SESSION['alfabank_login'] = $_POST['alfabank_login'];
                } elseif ($paymentMethod == 'qiwi') {
                    $_SESSION['qiwi_phone'] = $_POST['qiwi_phone'];
                }
            }

            if (isset($form_state['values']['panes']['payment']['details']['customer_name'])) {
                $customerName = trim($form_state['values']['panes']['payment']['details']['customer_name']);
                $parts        = preg_split('/\s+/', $customerName);
                if ($customerName
                    && count($parts) != 3
                ) {
                    form_set_error('customer_name', t('Payer\'s name is entered incorrectly.'));
                }
            }

            return;
            break;
        case 'settings':
            $form['yauc_settings'] = array(
                '#type'  => 'markup',
                '#value' => t('You shop ID. If you have any shops in you YooKassa account'),
            );

            return $form;
            break;
        case 'order-save':
            if (isset($_POST['panes']['payment']['details']['customer_name'])) {
                $customerName                 = $_POST['panes']['payment']['details']['customer_name'];
                $order->data['customer_name'] = $customerName;
                db_update('uc_orders')
                    ->fields(array('data' => serialize($order->data)))
                    ->condition('order_id', $order->order_id)
                    ->execute();
            }
            break;
    }
}

/**
 * Process successful payment to update Ubercart order.
 * Implements hook_yoomoney_api_process_payment_alter().
 *
 * @param array $payment
 */
function yoo_ubercart_api_yoomoney_api_process_payment_alter(&$payment)
{
    /** @var YooMoneyApiTransaction $transaction */
    $transaction = $payment['transaction'];
    $order       = uc_order_load($transaction->order_id);
    if ($order) {
        //print_r($order);
        uc_cart_complete_sale($order);
        uc_cart_empty($order->uid);
        uc_order_update_status($order->order_id, 'payment_received');
        $payment['success'] = true;
    } else {
        $payment['success'] = false;
        $payment['error']   = 'Can not find order with id '.$transaction->order_id;
    }
}

function yoo_ubercart_api_get_return_url($order)
{
    return url(
        'yoomoney_api/ubercart/return',
        array(
            'absolute' => true,
            'query'    => array('orderId' => $order->order_id),
        )
    );
}

function yoo_ubercart_api_theme()
{
    $items                                = array();
    $items['form_radio_element']          = array('render element' => 'element');
    $items['form_radios_element']         = array('render element' => 'element');
    $items['form_radio_element_external'] = array('render element' => 'element');

    return $items;
}

function yoo_ubercart_api_theme_registry_alter(&$theme_registry)
{
    $theme_registry['form_radios_element']['function']         = "theme_yoo_ubercart_api_form_radios_element";
    $theme_registry['form_radio_element']['function']          = "theme_yoo_ubercart_api_form_radio_element";
    $theme_registry['form_radio_element_external']['function'] = "theme_yoo_ubercart_api_form_radio_element_external";
}

function theme_yoo_ubercart_api_form_radios_element($variables)
{
    $element = $variables['element'];

    if ($element['#value'] == \YooKassa\Model\PaymentMethodType::ALFABANK) {
        $element['alfabank']['#theme'] = 'form_radio_element_external';
    } elseif ($element['#value'] == \YooKassa\Model\PaymentMethodType::QIWI) {
        $element['qiwi']['#theme'] = 'form_radio_element_external';
    }

    foreach (element_children($element) as $key) {

        if ($element[$key]['#theme'] !== 'form_radio_element_external') {
            $element[$key]['#theme'] = 'form_radio_element';
        }
        $element[$key]['#method_name'] = $element[$key]['#title'];
        $element[$key]['#title']       = '';
    }
    $items = drupal_render_children($element);

    return '<div '.drupal_attributes($element['#attributes']).'>'.$items.'</div>';
}

function theme_yoo_ubercart_api_form_radio_element($variables)
{
    $element                        = $variables['element'];
    $element['#attributes']['type'] = 'radio';
    element_set_attributes(
        $element,
        array(
            'id',
            'name',
            '#return_value' => 'value',
        )
    );
    if (isset($element['#return_value']) && $element['#value'] !== false && $element['#value'] == $element['#return_value']) {
        $element['#attributes']['checked'] = 'checked';
    }
    _form_set_class($element, array('form-radio'));
    $output = '<input'.drupal_attributes($element['#attributes']).' />';
    $output .= '<label for="'.$element['#id'].'" class="option">'.$element['#method_name'].'</label>';

    return '<div class="form-item form-type-radio">'.$output.'</div>';
}

function theme_yoo_ubercart_api_form_radio_element_external($variables)
{
    $element                        = $variables['element'];
    $element['#attributes']['type'] = 'radio';
    element_set_attributes(
        $element,
        array(
            'id',
            'name',
            '#return_value' => 'value',
        )
    );
    if (isset($element['#return_value']) && $element['#value'] !== false && $element['#value'] == $element['#return_value']) {
        $element['#attributes']['checked'] = 'checked';
    }
    _form_set_class($element, array('form-radio'));
    $output = '<input'.drupal_attributes($element['#attributes']).' />';
    $output .= '<label for="'.$element['#id'].'" class="option">'.$element['#method_name'].'</label>';

    if ($element['#value'] == 'alfabank') {
        $output .= '<div>';
        $output .= '<div>'.t('Specify the login, and we\'ll send the bill in Alfa-Click. All you have do after that is confirm the payment online at the bank\'s website.').'</div>';
        $output .= '<input type="text" name="alfabank_login">';
        $output .= '</div>';
    } elseif ($element['#value'] == 'qiwi') {
        $output .= '<div>';
        $output .= '<div>'.t('Phone number linked to Qiwi Wallet').'</div>';
        $output .= '<input type="text" name="qiwi_phone">';
        $output .= '</div>';
    }

    return '<div class="form-item form-type-radio">'.$output.'</div>';
}

function yoo_ubercart_ajax_payment_method_form_callback($form, $form_state)
{
    $form_state['rebuild'] = true;
    if ($form['panes']['payment']['details']['pay_method']['#value'] == 'qiwi') {
        $form['panes']['payment']['details']['pay_method']['qiwi']['#theme'] = 'form_radio_element_external';
    } else if ($form['panes']['payment']['details']['pay_method']['#value'] == 'alfabank') {
        $form['panes']['payment']['details']['pay_method']['alfabank']['#theme'] = 'form_radio_element_external';
    }

    return $form['panes']['payment']['details']['pay_method'];
}

/**
 * @param $orderInfo
 *
 * @return bool|string
 */
function yoo_ubercart_api_create_description($orderInfo)
{
    $descriptionTemplate = variable_get('yoomoney_api_description_template', t('Payment for order No. %order_id%'));

    $replace = array();
    foreach ($orderInfo as $key => $value) {
        if (is_scalar($value)) {
            $replace['%'.$key.'%'] = $value;
        }
    }

    $description = strtr($descriptionTemplate, $replace);

    return (string)mb_substr($description, 0, Payment::MAX_LENGTH_DESCRIPTION);
}

/**
 * @param \YooKassa\Model\PaymentInterface $payment
 * @param $order
 */
function yoo_ubercart_api_capture_payment($payment, $order)
{
    $apiClient = yoomoney_api__common__get_api_client();
    $response  = null;
    try {
        $builder = CreateCaptureRequest::builder();
        $amount  = $order->order_total;
        $builder->setAmount($amount);
        yoo_ubercart_api_set_receipt_if_needed($builder, $order);

        $request  = $builder->build();
        $response = $apiClient->capturePayment($request, $payment->getId());
    } catch (\Exception $e) {
        $this->module->log('error', 'Capture error: '.$e->getMessage());
        $response = $payment;
    }
    yoomoney_api_common_check_value_is_not_empty($response, '400 Bad Request', 'Empty payment info');
    if ($response->getStatus() !== \YooKassa\Model\PaymentStatus::SUCCEEDED) {
        $this->module->log('error', 'Capture payment error: capture failed');

        return;
    }
    yoomoney_api_update_transaction_status($response->getId(), $response->getStatus());
    uc_order_comment_save($order->order_id, 0, t('Вы подтвердили платёж в ЮKassa.'));

    echo "OK";
    exit();
}

/**
 * @param string $paymentId
 * @param $order
 */
function yoo_ubercart_api_cancel_payment($paymentId, $order)
{
    $apiClient = yoomoney_api__common__get_api_client();
    $response  = $apiClient->cancelPayment($paymentId);
    if (!$response || $response->getStatus() !== PaymentStatus::CANCELED) {
        $this->module->log('error', 'Cancel payment error: cancel failed');

        return;
    }

    uc_order_update_status($order->order_id, YOOMONEY_API_ORDER_STATUS_CANCELED);
    yoomoney_api_update_transaction_status($paymentId, PaymentStatus::CANCELED);
    uc_order_comment_save($order->order_id, 0, t('Вы отменили платёж в ЮKassa. Деньги вернутся клиенту.'));

    echo "OK";
    exit();
}
